export enum QUOTES_ACTION_TYPES {
  SET_COMPANY_INFO = 'SET_COMPANY_INFO',
  SET_COMPANY_NEWS = 'SET_COMPANY_NEWS',
  SET_COMPANY_STATS = 'SET_COMPANY_STATS',
  SET_COMPANY_EPS = 'SET_COMPANY_EPS',
  SET_DIVIDENDYIELD = 'SET_DIVIDENDYIELD',
  SET_TOP_PEERS = 'SET_TOP_PEERS',
  SET_CHART_DATA_DAY = 'SET_CHART_DATA_DAY',
  SET_CHART_DATA = 'SET_CHART_DATA',
  SET_COMPANY_NAMES = 'SET_COMPANY_NAMES',
}
