export const SET_COMPANY_INFO = 'SET_COMPANY_INFO';
export const SET_COMPANY_NEWS = 'SET_COMPANY_NEWS';
export const SET_COMPANY_STATS = 'SET_COMPANY_STATS';
export const SET_COMPANY_EPS = 'SET_COMPANY_EPS';
export const SET_DIVIDENDYIELD = 'SET_DIVIDENDYIELD';
export const SET_TOP_PEERS = 'SET_TOP_PEERS';
export const SET_CHART_DATA_DAY = 'SET_CHART_DATA_DAY';
export const SET_CHART_DATA = 'SET_CHART_DATA';
export const SET_COMPANY_NAMES = 'SET_COMPANY_NAMES';

export enum QUOTES_ACTION_TYPES {
  SET_COMPANY_INFO = 'SET_COMPANY_INFO',
  SET_COMPANY_NEWS = 'SET_COMPANY_NEWS',
  SET_COMPANY_STATS = 'SET_COMPANY_STATS',
  SET_COMPANY_EPS = 'SET_COMPANY_EPS',
  SET_DIVIDENDYIELD = 'SET_DIVIDENDYIELD',
  SET_TOP_PEERS = 'SET_TOP_PEERS',
  SET_CHART_DATA_DAY = 'SET_CHART_DATA_DAY',
  SET_CHART_DATA = 'SET_CHART_DATA',
  SET_COMPANY_NAMES = 'SET_COMPANY_NAMES',
}
